trigger:
- main

resources:
  repositories:
    - repository: template
      type: git
      name: DevOps
      ref: releases/1.0.0

pool:
  vmImage: Ubuntu-latest

variables:
  buildConfiguration: 'Release'

extends:
  template: dotnet6/build-and-deploy.yml@template
  parameters:
    solutionToBuild: 'Beis.Ebss.Document.Api.sln'
    projectToPublish: 'Beis.Ebss.Document.Api.csproj'
    webApplicationNameSuffix: 'document-api'
    webApplicationResourceGroupFormat: 'document-api'
    